version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    allow:
      - dependency-name: "@saas-maker/feedback"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 1
