import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const sourcePath = resolve(packageRoot, '../../catalog/generated/public.json');
const outputPath = resolve(packageRoot, 'src/catalog.ts');
const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const projects = source.products
  .filter((project) => project.url)
  .map((project) => ({
    id: project.id,
    name: project.name,
    url: project.url,
    description: project.description,
    tier: project.tier === 'core' ? 'focus' : project.tier,
    priority: project.priority,
    category: project.category,
    maturity: project.maturity,
    spotlight: project.spotlight,
    pillarId: project.pillarId,
    domains: [new URL(project.url).hostname],
  }));

// JSON is valid TypeScript syntax and safely escapes user-facing catalog copy.
// Keep the generated literal as JSON instead of converting strings to fragile
// single-quoted source.
const serialized = JSON.stringify(projects, null, 2);
const content = `// Generated by scripts/generate-catalog.mjs. Do not edit by hand.\nimport type { PortfolioProject } from './types';\n\nexport const DEFAULT_PROJECTS: readonly PortfolioProject[] = ${serialized};\n`;
await writeFile(outputPath, content);
console.log(`Generated ${projects.length} projects from ${sourcePath}`);
