export const TABLES = {
  users: 'users',
  projects: 'projects',
  feedback: 'feedback',
  feedback_votes: 'feedback_votes',
  sessions: 'sessions',
  knowledge_indexes: 'knowledge_indexes',
  documents: 'documents',
  document_chunks: 'document_chunks',
  waitlist_entries: 'waitlist_entries',
  analytics_events: 'analytics_events',
  forms: 'forms',
  form_questions: 'form_questions',
  form_responses: 'form_responses',
  form_answers: 'form_answers',
  testimonials: 'testimonials',
  changelog_entries: 'changelog_entries',
  cli_auth_codes: 'cli_auth_codes',
  cli_tokens: 'cli_tokens',
  ai_requests: 'ai_requests',
} as const;
