export const TABLES = {
  users: 'users',
  projects: 'projects',
  feedback: 'feedback',
  upvotes: 'upvotes',
  sessions: 'sessions',
  indexes: 'indexes',
  documents: 'documents',
  chunks: 'chunks',
  waitlist_entries: 'waitlist_entries',
  events: 'events',
  short_links: 'short_links',
  forms: 'forms',
  form_questions: 'form_questions',
  form_responses: 'form_responses',
  form_answers: 'form_answers',
} as const;
