// Generated by scripts/generate-catalog.mjs. Do not edit by hand.
import type { PortfolioProject } from './types';

export const DEFAULT_PROJECTS: readonly PortfolioProject[] = [
  {
    "id": "posttrainllm",
    "name": "PostTrainLLM",
    "url": "https://posttrainllm.com",
    "description": "An experimental browser model playground: run small language models locally with visible generation metrics.",
    "tier": "focus",
    "priority": "P1",
    "category": "product",
    "maturity": "experiment",
    "spotlight": true,
    "pillarId": "build",
    "domains": [
      "posttrainllm.com"
    ]
  },
  {
    "id": "field-track",
    "name": "Field Track",
    "url": "https://field-track.sassmaker.com",
    "description": "A labelled synthetic field-team demo for exploring routes, visits and agent summaries; Android tracking is not qualified.",
    "tier": "active",
    "priority": "P2",
    "category": "product",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "build",
    "domains": [
      "field-track.sassmaker.com"
    ]
  },
  {
    "id": "gitstat",
    "name": "GitStat",
    "url": "https://git.significanthobbies.com",
    "description": "An experimental public GitHub analysis tool for repository activity, contributions and code churn.",
    "tier": "secondary",
    "priority": "P2",
    "category": "product",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "build",
    "domains": [
      "git.significanthobbies.com"
    ]
  },
  {
    "id": "on-record",
    "name": "High Signal Podcasts",
    "url": "https://podcasts.highsignal.app",
    "description": "Search evidenced podcast claims and follow links back to the original episode or publication.",
    "tier": "active",
    "priority": "P2",
    "category": "product",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "learn",
    "domains": [
      "podcasts.highsignal.app"
    ]
  },
  {
    "id": "issue-pages",
    "name": "IssuePages",
    "url": "https://issues.sarthakagrawal.dev",
    "description": "Read public GitHub issues as focused articles; publishing requires repository-owner access.",
    "tier": "active",
    "priority": "P4",
    "category": "experiment",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "build",
    "domains": [
      "issues.sarthakagrawal.dev"
    ]
  },
  {
    "id": "live",
    "name": "Live",
    "url": "https://live.significanthobbies.com",
    "description": "A free personality and hobby quiz that suggests a small experiment to try; account planning is not yet qualified.",
    "tier": "active",
    "priority": "P2",
    "category": "personal",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "learn",
    "domains": [
      "live.significanthobbies.com"
    ]
  },
  {
    "id": "what-it-takes-to-win",
    "name": "Look Sideways",
    "url": "https://paths.significanthobbies.com",
    "description": "Explore sourced career turning points with explicit survivorship and forecasting limits.",
    "tier": "secondary",
    "priority": "P4",
    "category": "personal",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "learn",
    "domains": [
      "paths.significanthobbies.com"
    ]
  },
  {
    "id": "looptv",
    "name": "LoopTV",
    "url": "https://tv.significanthobbies.com",
    "description": "An experimental lean-back queue of curated science and other videos.",
    "tier": "secondary",
    "priority": "P4",
    "category": "personal",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "learn",
    "domains": [
      "tv.significanthobbies.com"
    ]
  },
  {
    "id": "materia",
    "name": "Materia",
    "url": "https://materia.significanthobbies.com",
    "description": "An educational body-and-remedy reference with condition-specific research citations and explicit uncertainty.",
    "tier": "active",
    "priority": "P4",
    "category": "experiment",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "build",
    "domains": [
      "materia.significanthobbies.com"
    ]
  },
  {
    "id": "veg-protein-food",
    "name": "Recipe Index",
    "url": "https://veg-protein-food.significanthobbies.com",
    "description": "Search vegetarian recipes by protein and calories, with links to the original recipe publishers.",
    "tier": "active",
    "priority": "P4",
    "category": "experiment",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "build",
    "domains": [
      "veg-protein-food.significanthobbies.com"
    ]
  },
  {
    "id": "research-papers",
    "name": "Research Papers",
    "url": "https://papers.highsignal.app",
    "description": "Search academic papers and follow original sources; account-based research chat is not yet qualified.",
    "tier": "secondary",
    "priority": "P2",
    "category": "product",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "learn",
    "domains": [
      "papers.highsignal.app"
    ]
  },
  {
    "id": "saas-maker",
    "name": "SaaS Maker",
    "url": "https://sassmaker.com",
    "description": "A public directory of working experiments, reference projects and reusable tooling.",
    "tier": "active",
    "priority": "P2",
    "category": "product",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "build",
    "domains": [
      "sassmaker.com"
    ]
  },
  {
    "id": "sarthakagrawal-personal",
    "name": "Sarthak Agrawal",
    "url": "https://sarthakagrawal.dev",
    "description": "Selected engineering case studies, technical writing and working project demonstrations.",
    "tier": "secondary",
    "priority": "P4",
    "category": "personal",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "personal",
    "domains": [
      "sarthakagrawal.dev"
    ]
  },
  {
    "id": "starboard",
    "name": "Starboard",
    "url": "https://starboard.codevetter.com",
    "description": "Explore public GitHub repositories and related projects through a searchable discovery experiment.",
    "tier": "secondary",
    "priority": "P2",
    "category": "product",
    "maturity": "experiment",
    "spotlight": false,
    "pillarId": "learn",
    "domains": [
      "starboard.codevetter.com"
    ]
  }
];
