name = "saasmaker-api"
main = "src/index.ts"
compatibility_date = "2026-02-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
binding = "FEEDBACK_IMAGES"
bucket_name = "saasmaker-feedback-images"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "8fb9b798a1804fa9bcd87c219f547656"
